-- MySQL Script generated by MySQL Workbench
-- Tue Sep 10 18:05:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema testedevell
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testedevell
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testedevell` DEFAULT CHARACTER SET latin1 ;
USE `testedevell` ;

-- -----------------------------------------------------
-- Table `testedevell`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`estado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`cidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `idEstado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Cidade_Estado` (`idEstado` ASC) VISIBLE,
  CONSTRAINT `FK_Cidade_Estado`
    FOREIGN KEY (`idEstado`)
    REFERENCES `testedevell`.`estado` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `idCidade` INT(11) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(30) NULL DEFAULT NULL,
  `bairro` VARCHAR(120) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(120) NULL DEFAULT NULL,
  `idAssociacao` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Cliente_Associacao` (`idAssociacao` ASC) VISIBLE,
  INDEX `FK_Cliente_Cidade` (`idCidade` ASC) VISIBLE,
  CONSTRAINT `FK_Cliente_Associacao`
    FOREIGN KEY (`idAssociacao`)
    REFERENCES `testedevell`.`associacao` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Cliente_Cidade`
    FOREIGN KEY (`idCidade`)
    REFERENCES `testedevell`.`cidade` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idPerfil` INT(11) NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `idFirebase` VARCHAR(255) NULL DEFAULT NULL,
  `authKey` VARCHAR(32) NOT NULL,
  `passwordHash` VARCHAR(255) NOT NULL,
  `passwordResetToken` VARCHAR(255) NOT NULL,
  `createdAt` BIGINT(20) NOT NULL,
  `updatedAt` BIGINT(20) NOT NULL,
  `status` TINYINT(4) NOT NULL DEFAULT '1',
  `idCliente` INT(11) NULL DEFAULT NULL,
  `username` VARCHAR(60) NOT NULL,
  `imagem` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Usuario_Cliente` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `FK_Usuario_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `testedevell`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`associacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`associacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `idCidade` INT(11) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(30) NULL DEFAULT NULL,
  `bairro` VARCHAR(120) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(120) NULL DEFAULT NULL,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Associacao_Cidade` (`idCidade` ASC) VISIBLE,
  CONSTRAINT `FK_Associacao_Cidade`
    FOREIGN KEY (`idCidade`)
    REFERENCES `testedevell`.`cidade` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Associacao_Usuario`
    FOREIGN KEY (`id`)
    REFERENCES `testedevell`.`usuario` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`credordevedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`credordevedor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `cnpj` VARCHAR(14) NULL DEFAULT NULL,
  `idCidade` INT(11) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `complemento` VARCHAR(30) NULL DEFAULT NULL,
  `bairro` VARCHAR(120) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(120) NULL DEFAULT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_CredorDevedor_Cidade` (`idCidade` ASC) VISIBLE,
  INDEX `FK_CredorDevedor_Cliente` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `FK_CredorDevedor_Cidade`
    FOREIGN KEY (`idCidade`)
    REFERENCES `testedevell`.`cidade` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_CredorDevedor_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `testedevell`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`formapagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`formapagamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`planoconta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`planoconta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `idPai` INT(11) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PlanoConta_Pai` (`idPai` ASC) VISIBLE,
  INDEX `FK_PlanoConta_Cliente` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `FK_PlanoConta_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `testedevell`.`cliente` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_PlanoConta_Pai`
    FOREIGN KEY (`idPai`)
    REFERENCES `testedevell`.`planoconta` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`tipoconta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`tipoconta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`tipodocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`tipodocumento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`lancamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`lancamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` TINYINT(4) NOT NULL,
  `idCredorDevedor` INT(11) NOT NULL,
  `numDocumento` VARCHAR(40) NULL DEFAULT NULL,
  `dtVencimento` DATE NULL DEFAULT NULL,
  `dtEmissao` DATE NULL DEFAULT NULL,
  `dtRealizacao` DATE NULL DEFAULT NULL,
  `valorPrevisto` DOUBLE NULL DEFAULT NULL,
  `valorRealizado` DOUBLE NULL DEFAULT NULL,
  `idBanco` INT(11) NOT NULL,
  `idTipoDocumento` INT(11) NOT NULL,
  `idFormaPagamento` INT(11) NOT NULL,
  `idTipoConta` INT(11) NOT NULL,
  `idPlanoConta` INT(11) NOT NULL,
  `descricao` VARCHAR(120) NULL DEFAULT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Lancamento_CredorDevedor` (`idCredorDevedor` ASC) VISIBLE,
  INDEX `FK_Lancamento_PlanoConta` (`idPlanoConta` ASC) VISIBLE,
  INDEX `FK_Lancamento_FormaPagamento` (`idFormaPagamento` ASC) VISIBLE,
  INDEX `FK_Lancamento_TipoDocumento` (`idTipoDocumento` ASC) VISIBLE,
  INDEX `FK_Lancamento_TipoConta` (`idTipoConta` ASC) VISIBLE,
  INDEX `FK_Lancamento_Cliente` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `FK_Lancamento_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `testedevell`.`cliente` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Lancamento_CredorDevedor`
    FOREIGN KEY (`idCredorDevedor`)
    REFERENCES `testedevell`.`credordevedor` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Lancamento_FormaPagamento`
    FOREIGN KEY (`idFormaPagamento`)
    REFERENCES `testedevell`.`formapagamento` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Lancamento_PlanoConta`
    FOREIGN KEY (`idPlanoConta`)
    REFERENCES `testedevell`.`planoconta` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Lancamento_TipoConta`
    FOREIGN KEY (`idTipoConta`)
    REFERENCES `testedevell`.`tipoconta` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Lancamento_TipoDocumento`
    FOREIGN KEY (`idTipoDocumento`)
    REFERENCES `testedevell`.`tipodocumento` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`banco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `agencia` VARCHAR(20) NULL DEFAULT NULL,
  `conta` VARCHAR(20) NULL DEFAULT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Banco_Cliente` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `FK_Banco_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `testedevell`.`cliente` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_Banco_Lancamento`
    FOREIGN KEY (`id`)
    REFERENCES `testedevell`.`lancamento` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`categoriaresultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`categoriaresultado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `prazoRecebimento` INT(11) NOT NULL DEFAULT '0' COMMENT 'Em meses',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Os resultados mensais são agrupados em a vista, a prazo, etc...';


-- -----------------------------------------------------
-- Table `testedevell`.`resultadomensal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`resultadomensal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ano` INT(11) NOT NULL,
  `mes` INT(11) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `idCategoriaResultado` INT(11) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ResultadoMensal_CategoriaResultado` (`idCategoriaResultado` ASC) VISIBLE,
  INDEX `FK_ResultadoMensal_Cliente` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `FK_ResultadoMensal_CategoriaResultado`
    FOREIGN KEY (`idCategoriaResultado`)
    REFERENCES `testedevell`.`categoriaresultado` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_ResultadoMensal_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `testedevell`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `testedevell`.`retencao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testedevell`.`retencao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ano` INT(11) NOT NULL,
  `mes` INT(11) NOT NULL,
  `valor` DOUBLE NOT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Retencao_id` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `FK_Retencao_id`
    FOREIGN KEY (`idCliente`)
    REFERENCES `testedevell`.`cliente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
